
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deploy # match the Deployment name in 02-deploy-for-hpa.yaml
  minReplicas: 1
  maxReplicas: 3
  # hpa metrics: TARGET x%/10%
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10  
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 10  