
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: nginx
        image: vinsdocker/nginx-gke # modified nginx image, tells which pod is serving the request
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
---
# pod for debug, run in exec mode and send the requsts to Service
# since Service is ONLY accessible within the cluster, use this pod to send the requsts
apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: debug
    image: vinsdocker/util
    args:
    - "sleep"
    - "3600"
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"


# run: `kubectl apply -f 03-svc-load-balancing.yaml`

# get the bash of debug-pod: `kubectl exec -it debug-pod -- bash`
  ## send the request to Service: `curl my-service` -> return the pod name which serving the request
  ## send request multiple times: -> each time may return different pod name -> the rquests were being load balanced
  ## the Service load balancing is random, not round robin