

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
spec:
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: order-service
  replicas: 3
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vinsdocker/k8s-app:v2
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - name: "app-port"
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: order-service
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: debug
    image: vinsdocker/util
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    args:
    - "sleep"
    - "3600"

# run: `kubectl apply -f 05-....`
# open exec mode in debug-pod: `kubectl exec -it debug-pod -- bash`
  ## run the command: `for i in {1..1000}; do curl -s http://my-service | grep -o "<title>[^<]*" | tail -c+8; done`
    ### send curl request 1000 times, grep and print <title>, output -> v1

# update app version: `k8s-app:v2`
  ## rolling update: v1 v1 v1 v2 v2 v1 v1 v2 v1 v1 .... v2 v2 v2 <- eventually v2
