
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  # replicaSet properties
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  # Pod template
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        
# run deployment: `kubectl apply -f 01-simple-deploy.yaml`