

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v3"
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 2
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vinsdocker/k8s-app:v3
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - name: "app-port"
          containerPort: 80

# run deployment: `kubectl apply -f 03-deploy-rollout.yaml`

# port forward: `kubectl port-forward deploy/order-service-deploy 8080:80`
  ## web -> `localhost:8080` -> v1

# update to `k8s-app:v2`
  ## run deployment and prot forward again
  ## web -> `localhost:8080` -> v2

# update to `k8s-app:v3`
  ## run deployment and prot forward again
  ## web -> `localhost:8080` -> v3

# get rollout history: `kubectl rollout history deploy/order-service-deploy`
  ## revision: 1 2 3

# to roll back to previous deployment: `kubectl rollout undo deploy/order-service-deploy`
  ## replicaSet rolled back to previous

# get rollout history: `kubectl rollout history deploy/order-service-deploy`
  ## revision 1 3 4 -> current revision(2) becomes the latest revision(4)

# roll back again: `kubectl rollout undo deploy/order-service-deploy`
  ## get rollout history: `kubectl rollout history deploy/order-service-deploy`
    ### revision: 1 4 5
    ### app revisied to `v3` instead of `v1`
    ### rollback stuck at last 2 revisions

# to roll back to a specific revision(e.g. 1): `kubectl rollout undo deploy/order-service-deploy --to-revision=1`

# get detailed history of a specific revision(what had been changed): `kubectl rollout history deploy --revision=5`