
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  # a simple way to tell that a hardcoded wait time to tell that the application need xx seconds to be ready
  # better way to do this is through probes
  minReadySeconds: 10
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"