
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
spec:
  minReadySeconds: 10
  # deploy strategy: recreate -> terminate old pods first then create new pods
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: order-service
  replicas: 3
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vinsdocker/k8s-app:v1
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - name: "app-port"
          containerPort: 80

# run deployment v1: `kubectl apply -f 05-deploy-recreate.yaml`

# update app version to v2: `k8s-app:v2`
# run deployment v2: `kubectl apply -f 05-deploy-recreate.yaml`
  ## old pods terminate first
  ## then create new pods

