
# deployment strategy: RollingUpdate
# maxSurge

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # maxSurge: "100%" # 100% - double the replica - 3 old pods and 3 new pods
      maxSurge: 1 # 1 extra pod(new) temporary
  selector:
    matchLabels:
      app: order-service
  replicas: 3
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vinsdocker/k8s-app:v2
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - name: "app-port"
          containerPort: 80

# run deployment v1: `kubectl apply -f 06-deploy-max-surge.yaml`

# update app version to v2: `k8s-app:v2`
# run deployment v2
  ## temporary, both 3 old pods and 3 new pods are running
  ## then 3 old pods were terminated