
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ss
spec:
  serviceName: nginx-service
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14


# run: `kubectl apply -f 04-...`
  ## pods were created one by one gradually
  ## pod name use `StatefulSet` - ss and adds index
  ## after deleting a pod, another pod created with exact name

# when update `replicas` to 1, the pods were deleted from end index

# upgrade image version `nginx:1.15`
  ## image update one by one gradually from end index