apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ss
spec:
  serviceName: nginx-service # tell the StatefulSet which service will be sending the request
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: nginx
        image: vinsdocker/nginx-gke
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  # type default to ClusterIP, but do not assign the IP address
  # to make the Headless Service
  type: ClusterIP
  clusterIP: None # headless service
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: demo
    image: vinsdocker/util
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    args:
    - "sleep"
    - "3600"        


# run: `kubectl apply -f 06-...`
  ## service/nginx-service   ClusterIP   None  ...

# exec: `kubectl exec -it demo-pod -- bash`
  ## get all pods IP addresses: `nslookup nginx-service`
  ## get IP address of a specific pod: `nslookup my-ss-0.nginx-service`
    ### DNS records were created as `<pod_name>.<service_name>`

# to send reqeust to a specific pod: `curl my-ss-0.nginx-service`
