
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: mongo
    image: mongo
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    # startupProbe using tcpSocket, to check if service is listening on specific port(mongo port: 27017)
    startupProbe:
      tcpSocket:
        port: 27018 # to fail, set to another port other than 27017
      periodSeconds: 1
      failureThreshold: 5

# run: `kubectl apply -f 02-...`

# to make the startup probe fail, set mongo port to 27018(any value other than 27017)
  ## pod fail and check the reason: `kubectl describe pod`: startup probe failed, connection refuse