

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    # startupProbe using exec, better option: httpGet / tcpSocket
    startupProbe:
      exec:
        # command to execute
        command:
        - "cat"
        - "/usr/share/nginx/html/index.html" # to fail: "dummy.txt"
      periodSeconds: 1
      failureThreshold: 3

