apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  appUrl: "http://app-url"
  timeout: "30"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    # inject whole configMap as env
    envFrom:
    - configMapRef:
        name: app-properties
    args:
    - env          

# run: `kubectl apply -f 02-...`

# check log: `kubectl logs my-pod`: env variables appUrl & timeout were injected