
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  # base-64 encoded
  username: YWRtaW4=
  password: UGFzc3dvcmQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    # inject secret as env
    env:
    - name: "app_username"
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: username
    - name: "app_password"
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: password
    args:
    - env            

# run: `kubectl apply -f 04-...`

# check log: `kubectl logs my-pod`: output both username & password env variables, with decoded value