
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local-cluster
nodes:
- role: control-plane
  # master node - port mapping - mapping host port 30001 to container port 30001(this is the NodePort)
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
- role: worker
- role: worker

# then run: kind create cluster --config kind-cluster.yaml
# to delete cluster: kind delete cluster --name local-cluster