
apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    env: # passing env variables
    - name: "request.timeout"
      value: "10ms"
    - name: "spring.profiles.active"
      value: "dev"
    args: # run env command
    - "env" 