
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: nginx
    image: nginx
  - name: ubuntu
    image: ubuntu
    args:
    - "sleep"
    - "3600"